version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
    groups:
      dev-dependencies:
        patterns:
          - "black"
          - "ruff"
          - "pytest*"
          - "wheel"
