name: servicelayer

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Show ref
      run: |
        echo "$GITHUB_REF"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
        BOTO_CONFIG: /dev/null
        AWS_ACCESS_KEY_ID: banana
        AWS_SECRET_ACCESS_KEY: bananacake
      run: |
        sudo rm -f /etc/boto.cfg
        sudo apt-get -qq update
        sudo apt-get install -y libicu-dev
        pip install pytest pytest-env pytest-cov pytest-mock wheel
        pip install -e ".[dev]"
    - name: Run the tests
      run: |
        make test
    - name: Build a distribution
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_password }}