name: servicelayer

on: [push]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Show ref
      run: |
        echo "$GITHUB_REF"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: make dev
    - name: Run the code format check
      run: make format-check
    - name: Run the linter
      run: make lint
    - name: Run the tests
      # Some tests rely on the package being installed
      run: docker compose run --rm shell bash -c "make install && make tests"
    - name: Build a distribution
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_password }}
